import { 
    Smartphone, 
    Home, 
    Tv2,
    Shirt, 
    Dumbbell, 
    Sparkles, 
    BookOpen, 
    Gamepad2, 
    Car, 
    Baby,
    Grid3X3,
    Drill,
    ShoppingBasket,
    Rocket,
    Dog,
    Cat,
    HardDrive,
    Github ,
    LucideSmartphone
    
} from "lucide-react";

export const categoryIcons = {
    eletronicos: Smartphone,
    eletrodomesticos: Tv2,
    hardware: HardDrive,
    games: Gamepad2,
    casa: Home,
    acessorios: Shirt,
    "moda feminina": Cat,
    "moda masculina": Dog,
    esporte: Dumbbell,
    "saude e beleza": Sparkles,
    livros: BookOpen,
    automotivo: Car,
    ferramentas: Drill,
    brinquedos: Rocket,
    mercado: ShoppingBasket,
    infantil: Baby,
    pet: Github,
    smartphone: LucideSmartphone,
    outros: Grid3X3
};

export const categoryLabels = {
    eletronicos: "Eletrônicos",
    eletrodomesticos : "Eletrodomésticos",
    hardware: "Hardware",
    games: "Games",
    casa: "Casa",
    acessorios: "Acessorios",
    "moda feminina": "Moda Feminina",
    "moda masculina": "Moda Masculina",
    esporte: "Esporte",
    "saude e beleza": "Saúde e Beleza",
    livros: "Livros",
    brinquedos: "Brinquedos",
    mercado: "Mercado",
    infantil: "Infantil",
    automotivo: "Automotivo",
    ferramentas: "Ferramentas",
    pet: "Pet",
    smartphone: "Smartphone",
    outros: "Outros"
};